import { randomUUID } from 'node:crypto';
import path from 'node:path';
import Database from 'better-sqlite3';
import { afterAll, beforeAll, expect, it } from 'vitest';
import { createChatArtifactBlobStore } from '../../src/chat-artifacts/blob-store.js';
import { attachChatArtifactThumbnail } from '../../src/chat-artifacts/run-capture.js';
import { cleanupIsolatedDataRoot, loadIsolatedServerModule, multiUserOptions, provisionAccounts,
  startMultiUserDaemon, type Principal, type StartedMultiUserDaemon } from './multiuser-harness.js';
import { PERSONAL_CODEX_MOCK, linkCodex } from './personal-codex-helpers.js';

let daemon: StartedMultiUserDaemon;
let root: string;
let a: Principal;
let b: Principal;
let admin: Principal;

beforeAll(async () => {
  ({ dataRoot: root } = await loadIsolatedServerModule());
  daemon = await startMultiUserDaemon(multiUserOptions({ testPersonalCodexAppServer: PERSONAL_CODEX_MOCK }));
  const accounts = await provisionAccounts(daemon, ['artifacts-a', 'artifacts-b']);
  [a, b] = accounts.users as [Principal, Principal]; admin = accounts.admin;
  await linkCodex(daemon, root, a, 'artifacts-a@example.test');
}, 120_000);
afterAll(async () => { await daemon?.close(); cleanupIsolatedDataRoot(); });

async function generated() {
  const projectId = randomUUID();
  const made = await daemon.request({ method: 'POST', path: '/api/projects', cookie: a.cookie, body: { id: projectId, name: 'Artifacts' } });
  expect(made.status).toBe(200);
  const conversationId = made.json.conversationId as string;
  const started = await daemon.request({ method: 'POST', path: '/api/runs', cookie: a.cookie, body: {
    projectId, conversationId, agentId: 'codex', executionSource: 'personal_subscription',
    message: '[mock-write=hero.png] [mock-write=page.html]',
  } });
  expect(started.status).toBe(202);
  const runId = started.json.runId as string;
  const events = await daemon.request({ path: `/api/runs/${runId}/events`, cookie: a.cookie });
  expect(events.text).toContain('"status":"succeeded"');
  const transcript = await daemon.request({ path: `/api/projects/${projectId}/conversations/${conversationId}/messages`, cookie: a.cookie });
  const message = transcript.json.messages.find((m: { role: string }) => m.role === 'assistant');
  return { projectId, conversationId, runId, message };
}

it('freezes run media before terminal SSE and serves exact history through the shared artifact APIs', async () => {
  const { projectId, conversationId, runId, message } = await generated();
  expect(message.producedFiles).toEqual(expect.arrayContaining([
    expect.objectContaining({ name: 'hero.png', path: 'hero.png', kind: 'image', size: expect.any(Number), mtime: expect.any(Number) }),
    expect.objectContaining({ name: 'page.html', path: 'page.html', kind: 'html' }),
  ]));
  expect(JSON.stringify(message.producedFiles)).not.toContain(root);
  const ref = message.artifactRefs.find((item: { label: string }) => item.label === 'hero.png');
  expect(ref).toMatchObject({ displayPolicy: 'immutable_snapshot', snapshotState: 'ready' });
  const prefix = `/api/projects/${projectId}`;
  const content = await daemon.request({ path: ref.snapshotUrl, cookie: a.cookie });
  expect(content.status, content.text).toBe(200);
  expect(content.text).toMatch(/^generated by /u);
  expect(content.headers['cache-control']).toBe('no-store');
  expect(content.headers['content-security-policy']).toContain('sandbox');
  expect(content.headers['access-control-allow-origin']).toBeUndefined();
  const meta = await daemon.request({ path: `${prefix}/chat-artifact-snapshots/${ref.snapshotId}`, cookie: a.cookie });
  expect(meta.json.snapshot).toMatchObject({ projectId, runId, state: 'ready', sourcePathAtCapture: 'hero.png' });
  const refs = await daemon.request({ path: `${prefix}/conversations/${conversationId}/messages/${message.id}/artifacts`, cookie: a.cookie });
  expect(refs.json.artifacts).toEqual(message.artifactRefs);
  expect((await daemon.request({ method: 'POST', path: `${prefix}/files`, cookie: a.cookie,
    body: { name: 'hero.png', content: 'new workspace bytes' } })).status).toBe(200);
  const historical = await daemon.request({ path: ref.snapshotUrl, cookie: a.cookie, headers: { 'if-none-match': content.headers.etag as string } });
  expect(historical.status).toBe(200); // No browser cache can substitute a previous identity's bytes.
  expect(historical.text).toBe(content.text);
  const workspace = await daemon.request({ path: `${prefix}/workspace-artifacts/${ref.workspaceArtifactId}`, cookie: a.cookie });
  expect(workspace.json.artifact).toMatchObject({ projectId, currentPath: 'hero.png', deleted: false });
  for (const response of [meta, refs, workspace]) {
    expect(response.text).not.toContain(root);
    expect(response.text).not.toContain('objects/');
  }
});

it('rejects foreign and missing artifact requests identically, including admins and ids inside an owned project', async () => {
  const { projectId, conversationId, message } = await generated();
  expect(message.artifactRefs).toHaveLength(2);
  const ref = message.artifactRefs.find((item: { label: string }) => item.label === 'hero.png');
  const suffixes = [`conversations/${conversationId}/messages/${message.id}/artifacts`,
    `chat-artifact-snapshots/${ref.snapshotId}`, `chat-artifact-snapshots/${ref.snapshotId}/content`,
    `chat-artifact-snapshots/${ref.snapshotId}/thumbnail`, `workspace-artifacts/${ref.workspaceArtifactId}`];
  for (const user of [b, admin]) for (const suffix of suffixes) {
    const foreign = await daemon.request({ path: `/api/projects/${projectId}/${suffix}`, cookie: user.cookie });
    const missing = await daemon.request({ path: `/api/projects/${randomUUID()}/${suffix}`, cookie: user.cookie });
    expect(foreign.status).toBe(404);
    expect(foreign.json).toEqual(missing.json);
  }
  const ownedId = randomUUID();
  expect((await daemon.request({ method: 'POST', path: '/api/projects', cookie: b.cookie,
    body: { id: ownedId, name: 'B' } })).status).toBe(200);
  for (const suffix of suffixes.slice(1)) {
    const foreign = await daemon.request({ path: `/api/projects/${ownedId}/${suffix}`, cookie: b.cookie });
    const resourceId = suffix.startsWith('workspace-artifacts/') ? ref.workspaceArtifactId : ref.snapshotId;
    const missing = await daemon.request({ path: `/api/projects/${ownedId}/${suffix.replace(resourceId, randomUUID())}`, cookie: b.cookie });
    expect(foreign.status).toBe(404);
    expect(foreign.json).toEqual(missing.json);
  }
});

it('serves captured covers with owner authority and never replaces an absent thumbnail with current bytes', async () => {
  const { projectId, message } = await generated();
  const ref = message.artifactRefs.find((item: { label: string }) => item.label === 'hero.png');
  const url = `/api/projects/${projectId}/chat-artifact-snapshots/${ref.snapshotId}/thumbnail`;
  expect((await daemon.request({ path: url, cookie: a.cookie })).status).toBe(404);
  const db = new Database(path.join(root, 'app.sqlite'));
  try {
    const captured = await attachChatArtifactThumbnail({ db, blobs: createChatArtifactBlobStore({ dataDir: root }) },
      { messageArtifactId: ref.id, bytes: Buffer.from('immutable cover bytes'), mime: 'image/png' });
    expect(captured.state).toBe('ready');
  } finally { db.close(); }
  const thumbnail = await daemon.request({ path: url, cookie: a.cookie });
  expect(thumbnail.status).toBe(200);
  expect(thumbnail.text).toBe('immutable cover bytes');
  expect(thumbnail.headers['cache-control']).toBe('no-store');
  expect((await daemon.request({ path: url, cookie: b.cookie })).status).toBe(404);
});
